// Versioned, tool-readable product help. Keep UI paths explicit so co-pilot
// never has to infer them from model memory.
export const FEATURE_GUIDE_VERSION = "2026-07-20";

type GuideEntry = { title: string; aliases: string[]; body: string };

const entries: Record<string, GuideEntry> = {
  "floor-editor": { title: "Floor editor", aliases: ["editor", "zones", "shapes", "rotate", "renumber", "floors", "underlay", "migration"], body: "Open Floor, then Edit Layout. Pick a zone, shape, and seat count before dragging a table onto the canvas; select a placed table to rotate it, change its shape or seats, move it to a zone, or tap its number to rename it. Add Floor creates another room. Floor migration turns a photo or screenshot into an editable starting layout with an underlay for corrections." },
  exclusions: { title: "Online and AI exclusions", aliases: ["online exclusion", "ai exclusion", "manual assign", "block online"], body: "On Floor, open a table or floor ⋮ menu. AI exclusion keeps that table or staff member out of automated seating and section assignment; online exclusion keeps a table or floor out of online availability. These are controls, not deletions, and can be reversed in the same menu." },
  "ai-seater": { title: "AI seater and Merge & Seat", aliases: ["ai seater", "seater", "auto seat", "merge and seat", "merge"], body: "Select a reservation or walk-in on the Floor, then use the existing seating flow. The seater recommends available capacity while honoring reservation holds, merge adjacency, table capacity, and server-load balance; it never seats a party until a human confirms. Merge & Seat combines nearby compatible tables for one party when a single table is not enough." },
  predictor: { title: "Predictor", aliases: ["forecast", "forecast factors", "research", "baseline"], body: "Open Predictor to generate a deterministic service forecast. It uses restaurant history, current bookings, staff and floor capacity, bounded research factors, and setup baseline inputs only while history is thin. The factors report shows which inputs were used or excluded; co-pilot only reads an already-cached forecast and never starts research." },
  "history-import": { title: "History import", aliases: ["import", "csv", "opentable", "resy", "history"], body: "Settings → Import history accepts reservation exports and other supported records. Review the extracted data, then commit it through the existing import flow. Imported history improves forecast accuracy; if there is no usable export, the baseline setup provides bounded temporary inputs instead." },
  briefing: { title: "Tonight's Game Plan", aliases: ["game plan", "briefing", "pre shift"], body: "On Predictor, use Tonight's Game Plan to create a pre-shift briefing. It combines an already available forecast, the reservation book, roster, and recorded history into demand, book, and staffing workstreams. Generate refreshes it; Re-generate intentionally bypasses the 30-minute restaurant-and-date cache." },
  copilot: { title: "Co-pilot and alerts", aliases: ["alerts", "copilot", "chat"], body: "Use the bottom-right Co-pilot button for read-only floor advice and feature help. It does not seat, edit, or save anything. While the current floor has seated parties, the lightweight alert sentry can surface a short advisory bubble; open it to see context, and it stays quiet during tours and dialogs." },
  team: { title: "Team and roles", aliases: ["team", "roles", "members", "staff"], body: "Settings → Team Management adds active staff and their roles. Roles are configurable in Settings and support dual-role staff. Team changes affect available roster and assignment controls but do not retroactively rewrite past service records." },
  roster: { title: "Shift roster and dual roles", aliases: ["roster", "shift", "dual role", "on shift"], body: "On Floor, use the staff sidebar to toggle who is on shift for the viewed service day. A lock or AI-excluded state keeps a person out of automated assignment. Staff with more than one role remain one person in the roster, so their coverage is not double-counted." },
  sections: { title: "Sections and assign modes", aliases: ["sections", "assign mode", "auto assign", "section view"], body: "On Floor, Assign mode lets you assign tables manually; Section View shows the resulting table ownership. Auto-Assign proposes balanced sections from the active roster while respecting exclusions. Review the result before service and adjust it manually at any time." },
  hours: { title: "Hours and days open", aliases: ["opening and closing time", "opening time", "closing time", "days open", "closed day", "hours"], body: "Settings → Hours lets you choose or type opening and closing times in the same control. The adjacent seven day toggles mark open and closed days. Forecasting labels a closed day with zero covers, so keep these settings aligned with the real service schedule." },
  "turn-time": { title: "Default turn time", aliases: ["turn time", "table turn", "default turn"], body: "Settings → Service defaults contains Default turn time. Choose a preset or keep the value supplied by baseline setup; non-preset values remain visible. It is a planning default, while recorded completed parties provide observed turn history." },
  seasons: { title: "Seasons", aliases: ["slow season", "busy season", "seasonality", "seasons"], body: "Settings → baseline setup lets you add Slow Season and Busy Season month ranges. Leave them blank when there is no regular season. While history is thin, these ranges apply bounded planning priors; enough recorded history silently takes over." },
  waitlist: { title: "Walk-ins and waitlist", aliases: ["walk in", "walk-in", "waitlist", "queue"], body: "Use Walk-In on the Floor or the Waitlist surface to add a party with a size and quoted wait. Select it to use the normal read-only seating recommendation, then a host confirms the table. Waiting, notified, seated, and left states stay in the service record." },
  "service-log": { title: "Service log corrections", aliases: ["service log", "correction", "now seated", "clear table"], body: "Open Service to review seated and completed parties for the viewed day. Select a party or its table to correct recorded details through the existing controls. Clear a table only after the party has departed so covers and turn information remain meaningful." },
  timeline: { title: "Timeline", aliases: ["timeline", "heatmap", "volume by time"], body: "Open Timeline for volume by time and the reservation-arrival heatmap. It reflects the selected service data and configured hours. Select a reservation from the timeline to inspect it on the floor." },
  calendar: { title: "Calendar", aliases: ["calendar", "future reservation", "past shift"], body: "Open Calendar and select any past, current, or future day. Selecting a day changes the floor and service context to that date; past days are history, future days are planning. Add future reservations and prepare future sections through the normal date-aware controls." },
  host: { title: "Host mode and PWA", aliases: ["host", "pwa", "install"], body: "Open /host for the host-stand surface: it uses the same restaurant session with a focused tab set and no restaurant creation or onboarding. Use the browser's install option to add the Host PWA where supported. Sign out from the host header before switching restaurants." },
  walkthrough: { title: "Walkthrough replay", aliases: ["replay tips", "tips", "walkthrough", "tour"], body: "Settings → Replay tips restarts manager feature tips for this restaurant. Host mode has a small ? control in its header for host tips. Setup walkthroughs are only for newly registered restaurants; existing restaurants do not receive them." },
  account: { title: "Sign-out and multi-restaurant", aliases: ["sign out", "logout", "different restaurant", "multi restaurant"], body: "Settings → Account shows the signed-in restaurant and Sign out. Confirming it clears the server session and performs a full navigation to login, so no in-memory floor or tour state survives. Sign in or create another restaurant from the manager login; host login is sign-in only." },
};

export const FEATURE_GUIDE_TOPICS = Object.entries(entries).map(([topic, entry]) => ({ topic, title: entry.title }));

export function getFeatureGuide(topic?: string) {
  const requested = String(topic || "").trim().toLowerCase();
  if (!requested || requested === "list" || requested === "topics") return { version: FEATURE_GUIDE_VERSION, topics: FEATURE_GUIDE_TOPICS };
  const found = Object.entries(entries).find(([key, entry]) => key === requested || entry.aliases.some((alias) => requested.includes(alias) || alias.includes(requested)));
  if (!found) return { version: FEATURE_GUIDE_VERSION, found: false, message: "No guide entry exists for that topic yet. Say so rather than guessing a UI path.", topics: FEATURE_GUIDE_TOPICS };
  return { version: FEATURE_GUIDE_VERSION, found: true, topic: found[0], title: found[1].title, guide: found[1].body };
}
